In [50]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.sparse as sparse
import sympy as sp
from sympy.utilities.lambdify import implemented_function

In [ ]:
# Creating a 3x3 matrix with NumPy
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matrix) # Print the matrix

In [ ]:
K = np.eye(10)
display(A)
K[0, :6] = np.array([0,1,2,3,4,5])
display(K)

In [ ]:
B = K
B[-1, -6:] = np.array([10, 9, 8, 7, 6, 5])
display(B)

In [ ]:
antall = 15
vektor = np.linspace(0, antall)
print(vektor)


In [ ]:

Nt = 10
A = np.eye(Nt)
A[0, :6] = 1, 0, 0, 0, 0, 0
A[-1, -6:] = 0, 0, 0, 0, 0, 1

b = np.zeros(Nt+1)
b[0] = 1
b[-1] = 1
u = sparse.linalg.spsolve(A.tocsr(), b)

In [ ]:
# If A is dense, convert it to a sparse matrix
A_dense = np.array([
    [3, 0, 0, 0, 1],
    [0, 4, 0, 0, 2],
    [0, 0, 5, 0, 0],
    [0, 0, 0, 6, 0],
    [1, 2, 0, 0, 7]
])

# Convert A to sparse matrix
A_sparse = sparse.csr_matrix(A_dense)

# Example right-hand side vector b
b_d = np.array([1, 2, 3, 4, 5])

# Solve the linear system A * u = b
u_d = sparse.linalg.spsolve(A_sparse, b_d)

print("Solution u:", u_d)

In [59]:
N = 6; L = 2; dx = L/N
D = sparse.diags([1, -2, 1], [-1, 0, 1], (N+1, N+1),'lil') #removed ,'lil')
#D[0, :3] = 2, -5, 4
#D[-1, -3:] = -1, 4, -5
D /= dx**2
D_dense = D.toarray()# Convert the sparse matrix to a dense array to display in full
print(D_dense)# Print the dense array

[[-18.   9.   0.   0.   0.   0.   0.]
 [  9. -18.   9.   0.   0.   0.   0.]
 [  0.   9. -18.   9.   0.   0.   0.]
 [  0.   0.   9. -18.   9.   0.   0.]
 [  0.   0.   0.   9. -18.   9.   0.]
 [  0.   0.   0.   0.   9. -18.   9.]
 [  0.   0.   0.   0.   0.   9. -18.]]


In [68]:
tom = sparse.diags([1, -20, 1], [-1, 0, 1], (N+1, N+1), 'lil') #removed ,'lil')
tom[0, :3] = 2, -5, 4
tom[-1, -3:] = -1, 4, -5
tom_dense = tom.toarray()# Convert the sparse matrix to a dense array to display in full
print(tom_dense)# Print the dense array

[[  2.  -5.   4.   0.   0.   0.   0.]
 [  1. -20.   1.   0.   0.   0.   0.]
 [  0.   1. -20.   1.   0.   0.   0.]
 [  0.   0.   1. -20.   1.   0.   0.]
 [  0.   0.   0.   1. -20.   1.   0.]
 [  0.   0.   0.   0.   1. -20.   1.]
 [  0.   0.   0.   0.  -1.   4.  -5.]]


In [ ]:
# Create a large matrix
matrix = np.random.rand(10, 10)  # Example with 10x10 matrix
np.set_printoptions(precision=3, suppress=True) # Set print options
print(np.array_str(D, max_line_width=np.inf))

In [ ]:
def pretty_print_matrix(D):
    for row in D:
        print(" ".join(f"{val:.3f}" for val in row))
# Call the pretty print function
pretty_print_matrix(D)

In [ ]:
rounded_matrix = np.round(D, decimals=1)
print(rounded_matrix)